name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy manifests to server
        uses: appleboy/scp-action@master
        with:
          host: home.meyssam.ir
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "kubernetes/*, scripts/*, airflow/dags/*"
          target: "~/deployment"

      - name: Apply Kubernetes manifests
        uses: appleboy/ssh-action@master
        with:
          host: home.meyssam.ir
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "ðŸ§¹ Cleaning up existing resources..."
            # Delete non-default resources in the current namespace
            # kubectl --insecure-skip-tls-verify=true delete deployments,services,pods,configmaps,pvc,statefulsets --all --ignore-not-found=true
            
            # Wait a moment for cleanup to finish
            sleep 5
            
            echo "ðŸš€ Deploying new manifests..."
            cd ~/deployment/kubernetes
            kubectl --validate=false --insecure-skip-tls-verify=true apply -f postgres-p1.yaml
            kubectl --validate=false --insecure-skip-tls-verify=true apply -f postgres-p2.yaml
            kubectl --validate=false --insecure-skip-tls-verify=true apply -f airflow.yaml
            kubectl --validate=false --insecure-skip-tls-verify=true apply -f jenkins.yaml
