name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy manifests to server
        uses: appleboy/scp-action@master
        with:
          host: home.meyssam.ir
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "kubernetes/*"
          target: "~/deployment"

      - name: Apply Kubernetes manifests
        uses: appleboy/ssh-action@master
        with:
          host: home.meyssam.ir
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ~/deployment/kubernetes
            kubectl apply -f postgres-p1.yaml
            kubectl apply -f postgres-p2.yaml
            kubectl apply -f airflow.yaml
            kubectl apply -f jenkins.yaml
